### ISSUE TITLE
gh-actions fails: 2.7 not available plus some black changes

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.recipe.zope2instance#194]
See [scheduled run](https://github.com/plone/plone.recipe.zope2instance/actions/runs/9633235504).

For 2.7 we probably need to specify a container.  Or drop support.  Copying a few lines from a buildout PR:

```
generate-scripts-py2:
    name: generate scripts - Python ${{ matrix.python-version }}
    strategy:
      matrix:
        package: [zest.releaser, pyspf]
        python-version: ["2.7"]
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    container:
      image: python:2.7.18-buster
```

I don't have time myself for the next few weeks, so if someone else wants to pick this up, I would appreciate it.
